-- Scale gates are fail-closed. Unknown is not treated as pass.
SELECT *
FROM (
  VALUES
    ('ios_crash_gate', 'iOS crash gate', 'blocked', 'Authenticated App Store Connect confirms one iOS 1.0.1 crash on 2026-08-25, but privacy suppression exposes no device, OS, crash report, stack, or UUID. Xcode Organizer also reports that a developer account is required to download the crash list, so symbolication and root-cause verification remain blocked.', 'Restore Organizer developer-account access or obtain the diagnostic report, then symbolicate, reproduce, fix, and re-smoke'),
    ('open_meteo_promotion_clearance', 'Open-Meteo promotion clearance', 'pending', 'Clarification email is drafted but has not been sent or answered.', 'Send through an authenticated sender and record an unambiguous written response'),
    ('release_artifact_source_sync', 'Release artifact source sync', 'blocked', 'Android phone 1.1.0 (8) and Apple 1.1.0 (6) are the current source identities. Protected signing material, compatible Apple profiles, and signing identities are present, but the Android security value lookups exit with status 51 and Apple archive codesign fails with errSecInternalComponent, backed by Security framework errSecAuthFailed. Neither current phone nor Apple candidate has a signed artifact, immutable hash, or matching physical-QA evidence; unchanged Wear OS 1.1.0 (1000008) alone remains verified-current. See growth/quality/signing-readiness-2026-08-29.md.', 'Restore private signing authorization without replacing the existing identities, then create new signed vc8 and build-6 artifacts, verify identities and hashes, and record exact physical QA'),
    ('android_physical_smoke', 'Android device smoke', 'blocked', 'An earlier same-day phone 1.1.0 (8) debug/source snapshot passed bounded API 25 onboarding, live weather, cached offline cold start, and stability checks. Subsequent provider-throttling and cross-path single-flight changes have no matching physical result, and there is still no upload-signed current artifact or release-certificate physical pass. The signed vc7 matrix is historical and does not transfer to vc8; physical tablet, widget, and Wear OS coverage also remains required.', 'Sign and verify phone vc8, then run the exact signed artifact on phone and tablet plus widget and paired Wear OS paths'),
    ('ios_physical_smoke', 'iOS physical smoke', 'blocked', 'Current Apple 1.1.0 (6) has only an unsigned arm64 simulator build and no distribution-signed archive, artifact hash, or physical result. The build-5 iPad install and build-4 bounded runtime evidence are historical and do not transfer; current iPhone, iPad, widget, and watch coverage remains required.', 'Archive and distribution-sign build 6, then run the exact artifact on iPhone and iPad plus widget and paired watch paths'),
    ('domain_activation', 'Domain activation', 'blocked', 'The registrar surface reports nimbo.uz is activating, registry WHOIS reports EXPIRED with creation and expiration both 2026-08-28, and authoritative plus public resolvers return DNSSEC NXDOMAIN. Cloudflare reports the zone pending with no DNS records. GitHub Pages is healthy, but registry delegation and TLS cannot proceed until registrar activation is complete.', 'Wait for registrar activation, then verify registry delegation, publish the reviewed Cloudflare DNS records, and wait for valid HTTPS'),
    ('store_policy_console_clearance', 'Store policy console clearance', 'pass', 'Read-only 2026-08-28 console check found no open App Store review/compliance action and Google Play Policy status explicitly reported no issues; see growth/quality/store-policy-console-2026-08-28.md.', 'Re-check both store policy surfaces with the next weekly UZ console evidence window')
) AS gates(gate_id, gate, status, evidence, next_action);
