-- Scale gates are fail-closed. Unknown is not treated as pass.
SELECT *
FROM (
  VALUES
    ('ios_crash_gate', 'iOS crash gate', 'blocked', 'Authenticated App Store Connect confirms one iOS 1.0.1 crash on 2026-08-25, but privacy suppression exposes no device, OS, crash report, stack, or UUID. Xcode Organizer also reports that a developer account is required to download the crash list, so symbolication and root-cause verification remain blocked.', 'Restore Organizer developer-account access or obtain the diagnostic report, then symbolicate, reproduce, fix, and re-smoke'),
    ('open_meteo_promotion_clearance', 'Open-Meteo promotion clearance', 'pending', 'Clarification was sent to Open-Meteo''s official contact at 2026-08-29 06:05 +05:00 from the authenticated maintainer account; no written reply has been received.', 'Monitor the sent thread and record an unambiguous written response'),
    ('release_artifact_source_sync', 'Release artifact source sync', 'blocked', 'Current product commit f97238b resolves to Android phone 1.1.0 (8) and Apple 1.1.0 (6). Its exact unsigned phone AAB SHA-256 a631c67df19761964d25dd6fbbdc89b7d9c0ee6d8544ebc23113bcee52043ed9 passes Bundletool validation with package uz.ganikhodjaev.weather, versionCode 8, versionName 1.1.0, minSdk 24, targetSdk 36, and 0 signature entries; mapping SHA-256 b25870ff3173eb6bccd0ee6bceffba098685d11aa828d27dc9f7a1965ec2c6c7 is retained. Exact-current Apple Release simulator executable SHA-256 values are app 67a99d6cfc04302c54aeb71fed0a78a6e3c6c9d9aaaca7bb4d0f1e13ed62bb58, embedded widget 3c65e9c8716a0f0426e19f2682b0d0ab1f1c0c0975106e773694d22600f72a4e, and watch app 75a329ed9ad25ae8fe25dcdb54afcd0b5828a9975d2056a9ec28bc079761713a. Those simulator products were built with CODE_SIGNING_ALLOWED=NO and have only ad-hoc linker signatures with no TeamIdentifier; they are not archives or upload candidates. A matching-source Android debug APK passed bounded physical API 25 and API 36 emulator QA, but it is not upload-signed or a full release matrix. Android Keychain value lookups exit with status 51, and Apple private-key signing remains unavailable after errSecInternalComponent and errSecAuthFailed evidence. There is no upload-signed phone AAB, distribution-signed Apple archive, or matching signed-artifact physical QA. Unchanged Wear OS 1.1.0 (1000008) alone remains verified-current. See growth/quality/signing-readiness-2026-08-29.md.', 'Restore private signing authorization without replacing the existing identities, then create new signed vc8 and build-6 artifacts, verify identities and hashes, and record exact physical QA'),
    ('android_physical_smoke', 'Android device smoke', 'blocked', 'Current product commit f97238b debug APK SHA-256 7b2f2c12d56fdda293f19317ef6eb6da153213f84b1daeef11fd35f8e9e30edb passed bounded current-source QA on the dedicated physical API 25 phone and API 36 emulator: onboarding, live city selection/search, share chooser, legacy navigation contrast, true-offline cache/error/recovery, IME resize, dark landscape, and process stability. The review prompt itself was not forced. There is still no upload-signed vc8 or release-certificate physical result, and physical tablet, widget, and Wear OS coverage remains required.', 'Sign and verify phone vc8, then run the exact signed artifact on phone and tablet plus widget and paired Wear OS paths'),
    ('ios_physical_smoke', 'iOS physical smoke', 'blocked', 'Current Apple 1.1.0 (6) source at commit f97238b now has exact-current arm64 Release simulator executable hashes: app 67a99d6cfc04302c54aeb71fed0a78a6e3c6c9d9aaaca7bb4d0f1e13ed62bb58, embedded widget 3c65e9c8716a0f0426e19f2682b0d0ab1f1c0c0975106e773694d22600f72a4e, and watch app 75a329ed9ad25ae8fe25dcdb54afcd0b5828a9975d2056a9ec28bc079761713a. They were built with CODE_SIGNING_ALLOWED=NO and carry only Xcode ad-hoc linker signatures with no TeamIdentifier, so they are not uploadable and provide no archive or physical-device proof. A current iPad has a compatible usable DDI and connected tunnel, but private-key signing still blocks installation; current iPhone, iPad, widget, and watch physical coverage remains required.', 'Archive and distribution-sign build 6, then run the exact artifact on iPhone and iPad plus widget and paired watch paths'),
    ('domain_activation', 'Domain activation', 'blocked', 'At 2026-08-29 08:12 +05:00, domain-specific WHOIS still reports NIMBO.UZ as EXPIRED with creation and expiration both 2026-08-28; the apparent top-level ACTIVE line belongs to the IANA .UZ ccTLD object, not NIMBO.UZ. Cloudflare remains pending, but both assigned child nameservers authoritatively serve the staged DNS-only GitHub Pages record set. Registry authorities and public resolvers return DNSSEC-validated non-delegation, with no public A or AAAA answer and no resolvable HTTPS host. One registrar support follow-up referencing ticket 1665 was sent at approximately 07:45; no later activation reply, DNS change, or duplicate message is recorded.', 'Wait for registrar activation, verify registry delegation and the staged records from independent resolvers, then wait for valid HTTPS'),
    ('store_policy_console_clearance', 'Store policy console clearance', 'pass', 'The 2026-08-28 App Store read-only check found no open review/compliance action, and the authenticated Google Play recheck at 2026-08-29 06:24 +05:00 again explicitly reported no policy issues and no pending publishing change. See growth/quality/store-policy-console-2026-08-28.md.', 'Re-check both store policy surfaces with the next weekly UZ console evidence window')
) AS gates(gate_id, gate, status, evidence, next_action);
